//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATM_Challenge.DTO.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Balance()
        {
            this.Amount = 0m;
        }
    
        public long IdBalance { get; set; }
        public long IdCard { get; set; }
        public System.DateTime RegDate { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Card Card { get; set; }
    }
}
